# Generated by Django 6.0.5 on 2026-05-28 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in webhook URL: /api/webhooks/whatsapp/{slug}/', unique=True)),
                ('wa_phone_number_id', models.CharField(max_length=64, unique=True)),
                ('wa_business_account_id', models.CharField(max_length=64)),
                ('wa_access_token', models.TextField(help_text='WhatsApp Cloud API access token')),
                ('wa_webhook_verify_token', models.CharField(max_length=128)),
                ('owner_phone', models.CharField(help_text='Phone number for sale alerts (with country code, e.g. 2348012345678)', max_length=32)),
                ('owner_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant'],
            },
        ),
    ]
