# Generated by Django 6.0.5 on 2026-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='wa_app_secret',
            field=models.CharField(default='', help_text='Meta App Secret — used to verify inbound webhook signatures', max_length=255),
            preserve_default=False,
        ),
    ]
