# Generated by Django 6.0.5 on 2026-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_wa_app_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='Tenant-editable extras: upsell rules, persona name tweaks, product-specific notes. Appended after platform instructions.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='platform_instructions',
            field=models.TextField(blank=True, help_text='Platform-level LLM instructions: persona, language rules, delivery constraints. Injected into the system prompt after core pricing/tool rules.'),
        ),
    ]
