# Generated by Django 6.0.5 on 2026-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_llm_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bot_paused',
            field=models.BooleanField(default=False, help_text="When True, the bot replies 'temporarily unavailable' to all customer messages."),
        ),
    ]
