# Generated by Django 6.0.5 on 2026-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_bot_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='classification_llm_provider',
            field=models.CharField(default='deepseek', help_text='LLM provider key for sentiment/intent classification', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='co_pilot_mode',
            field=models.CharField(choices=[('autonomous', 'Autonomous'), ('co_pilot', 'Co-Pilot')], default='autonomous', help_text='Default mode for new conversations: autonomous (bot replies directly) or co_pilot (bot drafts, owner approves)', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='follow_up_enabled',
            field=models.BooleanField(default=False, help_text='When True, post-purchase follow-up messages are sent to customers.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='follow_up_templates',
            field=models.JSONField(blank=True, default=dict, help_text='Customized follow-up message templates. Keys: day_1, day_5, day_14, day_30, cart_2h, cart_6h.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='personality',
            field=models.JSONField(blank=True, default=dict, help_text='Bot personality config: tone (friendly/professional/enthusiastic/casual/formal), formality (casual/professional/formal), emoji_level (none/moderate/liberal)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_llm_provider',
            field=models.CharField(default='deepseek', help_text='LLM provider key for response generation: deepseek, openai, anthropic', max_length=32),
        ),
    ]
