# Generated by Django 6.0.5 on 2026-06-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16),
        ),
    ]
