# Generated by Django 6.0.5 on 2026-08-09 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_co_pilot_mode_conversation_phase_and_more'),
        ('payments', '0002_add_refunded_status'),
        ('tenants', '0005_tenant_classification_llm_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSaleFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('day_1', 'Day 1 — Delivery Check-In'), ('day_5', 'Day 5 — Feedback Request'), ('day_14', 'Day 14 — Re-Engagement'), ('day_30', 'Day 30 — Win-Back'), ('cart_2h', 'Cart 2h — First Nudge'), ('cart_6h', 'Cart 6h — Second Nudge')], max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('message_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='conversations.conversation')),
                ('payment_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='payments.paymentlink')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='payments.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='tenants.tenant')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
