# Generated by Django 6.0.5 on 2026-06-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Product media'},
        ),
    ]
