# Generated by Django 6.0.5 on 2026-06-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productmedia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to disable stock tracking. When set, the bot is aware of remaining units and availability is auto-updated on sale.', null=True),
        ),
    ]
