# Generated by Django 6.0.5 on 2026-08-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_embedding'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS catalog_product_embedding_idx ON catalog_product USING hnsw (embedding vector_cosine_ops)",
            reverse_sql="DROP INDEX IF EXISTS catalog_product_embedding_idx",
        ),
    ]
