# Generated by Django 6.0.5 on 2026-06-28 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('sale', 'Sale confirmed'), ('escalation', 'Escalation alert'), ('stock_out', 'Stock out'), ('daily_digest', 'Daily digest')], default='sale', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.sale'),
        ),
    ]
