# Generated by Django 6.0.5 on 2026-05-28 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_wa_id', models.CharField(help_text="Customer's WhatsApp phone number", max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=32)),
                ('context_summary', models.TextField(blank=True, help_text='Written to DB when conversation ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('tenant', 'customer_wa_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('wa_message_id', models.CharField(blank=True, db_index=True, help_text='Used for deduplication', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
