# Generated by Django 6.0.5 on 2026-06-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('escalated', 'Escalated')], default='active', max_length=32),
        ),
    ]
