# Generated by Django 6.0.5 on 2026-08-09 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversation_state'),
        ('tenants', '0005_tenant_classification_llm_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='co_pilot_mode',
            field=models.CharField(choices=[('inherit', 'Inherit'), ('autonomous', 'Autonomous'), ('co_pilot', 'Co-Pilot')], default='inherit', help_text="Per-conversation override for co-pilot mode. 'inherit' uses the tenant default.", max_length=32),
        ),
        migrations.AddField(
            model_name='conversation',
            name='phase',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('discovery', 'Discovery'), ('recommendation', 'Recommendation'), ('negotiation', 'Negotiation'), ('close', 'Close')], default='greeting', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='Identifier for the prompt version that generated this message', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by_owner',
            field=models.BooleanField(default=False, help_text='True if sent by the business owner via dashboard'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('escalated', 'Escalated'), ('owner_handling', 'Owner Handling'), ('co_pilot_drafting', 'Co-Pilot Drafting')], default='active', max_length=32),
        ),
        migrations.CreateModel(
            name='BotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('edited', 'Edited')], max_length=16)),
                ('owner_note', models.TextField(blank=True)),
                ('edited_response', models.TextField(blank=True, help_text="Owner's corrected version when type is 'edited'")),
                ('context_snapshot', models.JSONField(default=list, help_text='Last 5 messages for context')),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='conversations.conversation')),
                ('message', models.ForeignKey(help_text='The bot message that received feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='conversations.message')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
